language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse unittest2; fi
    - "pip install requests mock --use-mirrors"
script: nosetests